`timescale 1ns/1ps

module doodle_jump #(
    parameter DATA_WIDTH = 16,
    parameter MEMORY_ADDR_WIDTH = 16
) (
    input  systemClock50MHz,
    input  [9:0] switches,
    output [9:0] leds,
    input  [3:0] push_buttons,
    output [6:0] hex0,
    output [6:0] hex1,
    output [6:0] hex2,
    output [6:0] hex3,
    output [6:0] hex4,
    output [6:0] hex5,
    inout  i2c_clock,
    inout  i2c_data,
    inout  audio_masterClock,
    inout  audio_leftRightClock,
    inout  audio_bitClock,
    inout  audio_data,
    output vga_clock,
    output vga_blank_n,
    output vga_hs,
    output vga_vs,
    output vga_sync_n,
    output [7:0] vga_red,
    output [7:0] vga_green,
    output [7:0] vga_blue,
    output [DATA_WIDTH-1:0] instructionRegisterContentsOutput,
    output [DATA_WIDTH-1:0] programCounterContentsOutput,
    output [DATA_WIDTH-1:0] programStateRegisterContentsOutput,
    output [DATA_WIDTH-1:0] aluResultOutput,
    output [4:0] aluFlagsOutput,
    output [2:0] controlUnitState,
    output [2:0] controlUnitNextState
);

    // Forward the board-facing pins into the integrated top-level system.
    doodle_jump_top doodle_jump_top_instance (
        .systemClock50MHz(systemClock50MHz),
        .switches(switches),
        .leds(leds),
        .push_buttons(push_buttons),
        .hex0(hex0),
        .hex1(hex1),
        .hex2(hex2),
        .hex3(hex3),
        .hex4(hex4),
        .hex5(hex5),
        .i2c_clock(i2c_clock),
        .i2c_data(i2c_data),
        .audio_masterClock(audio_masterClock),
        .audio_leftRightClock(audio_leftRightClock),
        .audio_bitClock(audio_bitClock),
        .audio_data(audio_data),
        .vga_clock(vga_clock),
        .vga_blank_n(vga_blank_n),
        .vga_hs(vga_hs),
        .vga_vs(vga_vs),
        .vga_sync_n(vga_sync_n),
        .vga_red(vga_red),
        .vga_green(vga_green),
        .vga_blue(vga_blue),
        .instructionRegisterContentsOutput(instructionRegisterContentsOutput),
        .programCounterContentsOutput(programCounterContentsOutput),
        .programStateRegisterContentsOutput(programStateRegisterContentsOutput),
        .aluResultOutput(aluResultOutput),
        .aluFlagsOutput(aluFlagsOutput),
        .controlUnitState(controlUnitState),
        .controlUnitNextState(controlUnitNextState)
    );

endmodule
